services:
  - type: web
    name: ecom-api
    runtime: dotnet
    region: singapore
    plan: free
    branch: main
    rootDir: src/Ecom.Api
    buildCommand: dotnet restore && dotnet publish -c Release -o out
    startCommand: cd out && dotnet Ecom.Api.dll
    healthCheckPath: /api/v1/health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        value: postgresql://ecom_user:3Ys0Sa5DXX8EGnjNHDyjFIvHj8c6TUKt@dpg-d3minmjuibrs73e0p9a0-a/ecom_dps0
      - key: SupabaseAuth__JwtIssuer
        value: https://rioqfyejijcvdteaglzo.supabase.co/auth/v1
      - key: SupabaseAuth__JwtAudience
        value: authenticated
      - key: SupabaseAuth__JwtSecret
        sync: false # Set in dashboard
      - key: Supabase__Url
        value: https://rioqfyejijcvdteaglzo.supabase.co
      - key: Supabase__AnonKey
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpb3FmeWVqaWpjdmR0ZWFnbHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNTgyMjYsImV4cCI6MjA3NTYzNDIyNn0.7tNhV8j2NlLjJ-kB6NN_SMhMBXbDpwFTENWRO8X8Vfg
      - key: Stripe__SecretKey
        sync: false # Set in dashboard
      - key: Stripe__WebhookSecret
        sync: false # Set in dashboard
      - key: Stripe__SuccessUrl
        value: https://httpbin.org/status/200?ok=1
      - key: Stripe__CancelUrl
        value: https://httpbin.org/status/200?cancel=1
      - key: FRONTEND_ORIGIN
        value: https://your-frontend.com
